### ISSUE TITLE
timeCodeWAS: na in hovering dots 

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperationsViewer#10]
most likely is bcs there are 0 controls
then created table is empty 
check that

**Comment by siirtola** [comment]
This is how it looks like in Eunomia. The problematic rows are 638,639 and 644.

![2024-04-04_08-39-30](https://github.com/FINNGEN/CohortOperationsViewer/assets/7419735/2ad1da33-cfdd-43cb-aed8-8ff1a0f99560)

**Comment by javier-gracia-tabuenca-tuni** [comment]
Harri Siirtola
  [1:50 PM](https://finngencommunity.slack.com/archives/DVC3JAN58/p1712573446732689)
In the input for TimeCodeWAS visualization (studyResult) there are three rows with NA as OR.
Those display "NA" as label.
They are all from [0,0] time range (edited)
