### ISSUE TITLE
Analysis: CodeWAS: Viewer

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperationsViewer#23]
duplicate codes from timeCodeWas

replace module to visualize timeCodeWAS with a new module for visualize codeWAS

Visualization can take code from https://github.com/tbilab/meToolkit
more info https://prod.tbilab.org/phewas_me_info/A_phewasME_in_depth_intro.html
demo https://prod.tbilab.org/phewas_me/

Example of a zip with codeWAS data 
[test_codeWAS.zip](https://github.com/FINNGEN/CohortOperationsViewer/files/14987496/test_codeWAS.zip)

it has 3 tables that may be used, these follow description similart to explained in 
https://prod.tbilab.org/phewas_me

i made these table to fit what the phewas_me may be using, these can change later, or we can make it to what we need

**Comment by javier-gracia-tabuenca-tuni** [comment]
i made the initial code
only thing missing is to format the raw table

**Comment by javier-gracia-tabuenca-tuni** [comment]
there is branch 23-analysis-codewas-viewer with some changes already 
move to the branch 
launch the app
import test file https://github.com/FINNGEN/CohortOperationsViewer/blob/23-analysis-codewas-viewer/tests/testthat/testdata/codeWAS/eunomia_asthmaVSasthmaControls_CodeWASSqlite.zip
navigate to 'codeWAS' menu

there is the raw table 
![image](https://github.com/FINNGEN/CohortOperationsViewer/assets/54809193/501c776b-ec98-4f57-838d-502173be629f)

this is rendered at this point in code
https://github.com/FINNGEN/CohortOperationsViewer/blob/dfcb400041c536575dd611019e67f5cae5ae4c28/R/mod_CodeWASVisualisation.R#L102

**Comment by javier-gracia-tabuenca-tuni** [comment]
TODO:

- decide what columns to show and in what order 
- format the table numbers and such correctly 
- links to Athena like in timeCodeWAS (concept id is calculated with covaraite id removing the last 3 digits)
- add menu with different filters , come to mind now
   - picker for analysis_name
   - picker for domain
   - covariate type, all, proportion, continuous
   - p_value (slider ?)
   - odds_ratio (slider ?)
 - Option to download the table as csv

**Comment by javier-gracia-tabuenca-tuni** [comment]
@mpreeve looking at the picture
do you have more filters to add ?

**Comment by javier-gracia-tabuenca-tuni** [comment]
for reference these are the filter in CohortDiagnostics for similar data
![image](https://github.com/FINNGEN/CohortOperationsViewer/assets/54809193/3b2d3e5d-5105-4d36-8ba7-489c55e5b454)

**Comment by javier-gracia-tabuenca-tuni** [comment]
Columns in this order 
- remove row number
- Database (  instead of DBid)
- Domain Name
- Analysis Name
- Covariate Name (instead of Cov Name)
- Concept Id (if id is not 0, to include a hiper link to to atlast for that code (this is how i did for timeCodeWAS https://github.com/FINNGEN/CohortOperationsViewer/blob/4186de5c4a445254b5a98b855d57ede2f09355d5/R/mod_TimeCodeWASPlot.R#L243)
- N cases (empty instead of NA)
- N Controls (empty instead of NA)
- p
- OR
- Beta
- SE
- Model
- Notes (empty instead of NA)

**Comment by javier-gracia-tabuenca-tuni** [comment]
Filters , 
- Picker Database
- Picker one or more Domains
- Picker one or more Analysis 
- Picker one or more Model
- filter for p value, other than slider, maybe bins like you did in TimeCodeWAS,  ?

**Comment by siirtola** [comment]
Some column names had to be shortened, but otherwise this should be working now.
