### ISSUE TITLE
Viewer: cohort Demographics: plots

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperationsViewer#29]
as in codeWAS and overlaps 
I got all ready except converting table to plot

https://github.com/FINNGEN/CohortOperationsViewer/blob/7545d73b5ff3efda87fb90daaefea1286502d8e3/R/mod_CohortDemographicsPlot.R#L23

Plot similar to CO1, old code here
https://github.com/FINNGEN/CohortOperationsShinyApp/blob/master/R/mod_compare_cohorts.R

**Comment by javier-gracia-tabuenca-tuni** [comment]
![image](https://github.com/FINNGEN/CohortOperationsViewer/assets/54809193/41b8a5e3-e36b-467b-b2a2-1c5287893a48)

CO1 for reference

**Comment by siirtola** [comment]
Is the use of plotly expected?

**Comment by javier-gracia-tabuenca-tuni** [comment]
Its up to you
________________________________
