### ISSUE TITLE
Viewer: Cohort Overlaps error

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/CohortOperationsViewer#30]
![Image](https://github.com/FINNGEN/CohortOperationsViewer/assets/54809193/720dd61c-989f-4442-90b8-3bba0cdee43e)

**Comment by siirtola** [comment]
It might have something to do how you start the shiny application:

https://stackoverflow.com/questions/74245044/error-c-stack-usage-15924224-is-too-close-to-the-limit

**Comment by siirtola** [comment]
This is perhaps the best explation, but I still don't understand what would use so much stack space? 
Also, why it works in the test environment but not in Docker? The stack limit is the same.

https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit?rq=4

**Comment by javier-gracia-tabuenca-tuni** [comment]
i think what use so much memory is this
UpSetR::fromExpression
seems not very efficient to spread a matrix of few  count values in a binary matrix with as many values as counts to later count them and plot the counts



![Image](https://github.com/FINNGEN/CohortOperationsViewer/assets/54809193/9a0fb411-61f4-47a3-b9a3-fc20bd44a379)

**Comment by siirtola** [comment]
I don't get it (first time I looked that function): why it is forming that matrix when all that is needed is in the expression? Why the re-count?

**Comment by siirtola** [comment]
Can you describe the input that caused the error? I can't get it to fail with any mock data that I have, the largest cohort being over 500,000 patients.

**Comment by javier-gracia-tabuenca-tuni** [comment]
solved, It was some flag on the docker file remaining form an other problem i tried to solve with Java running out of memory
i found it bcs it was working well when I ran it inside rstudio in sandbox

**Comment by siirtola** [comment]
Good! I am still wondering why the fromExpression builds the matrix? Is it a matter of trust – are they checking the expression does not contain conflicts?
